### PR TITLE
Additional details to make your PR on the original complete

### PR DESCRIPTION
**Pull request by prete**

### CODE REVIEW

**Review by zktuong — CHANGES_REQUESTED** [review]
Hi Martin, i think we should add `h5py<3.0.0` as `anndata<0.7.5` doesn't read properly for files saved with `h5py>2.10.0` last i checked https://github.com/theislab/anndata/issues/442. Most users would not be using anndata 0.7.5 at the moment either so perhaps we should change it to just `anndata>=0.7,<=0.75` and `h5py<3.0.0`.

**Comment by zktuong** [comment]
Also, i can't seem to find the code chunk uses a function from `scikit-learn==0.22` but this gives the `DepreciationWarning` related to `sklearn.cluster.k_means_` everytime cellphonedb is started, possibly linked to `geosketch`'s import of `scikit-learn`. Related to https://github.com/Teichlab/cellphonedb/issues/247. 

I can see from the latest `geosketch` release that they have allowed for `scikit-learn>=0.24` https://github.com/brianhie/geosketch/commit/770648898d9c1343eed5e12b846adcd120d0beba. Would be useful to update the current version from `geosketch==0.3` to `geosketch==1.2` if cellphonedb's code works with the latest version of `geosketch`.

What do you think?

**Comment by prete** [comment]
> i think we should add `h5py<3.0.0` as `anndata<0.7.5` 

Agree, I've added the version restriction to the requirements

> I can see from the latest `geosketch` release that they have allowed for `scikit-learn>=0.24` [brianhie/geosketch@7706488](https://github.com/brianhie/geosketch/commit/770648898d9c1343eed5e12b846adcd120d0beba). Would be useful to update the current version from `geosketch==0.3` to `geosketch==1.2` if cellphonedb's code works with the latest version of `geosketch`.

Actually, I made the PR for that upgrade 😅 I want to update geosketch to 1.2 but that requires more testing. In the meantime I think we've covered pretty much all that was needed for `v2.1.6` of CellphoneDB.

All that's left now is you merging this so I can accept the PR on Teichlab/cellphonedb create the release.

**Comment by zktuong** [comment]
sounds good!

**Pull request merged**
